In [52]:
import pandas as pd
import pickle

In [2]:
df=pd.read_csv('emotion-stimulus.csv.txt')
df.head()

Emotion                                               Text
0   happy  I suppose I am happy being so ` tiny' ; it mea...
1   happy  Lennox has always truly wanted to fight for th...
2   happy  He was a professional musician now , still sen...
3   happy  Holmes is happy having the freedom of the hous...
4   happy  I had problems with tutors trying to encourage...

In [3]:
df['Emotion'].value_counts()

sad         575
anger       483
happy       479
fear        423
surprise    213
shame       146
disgust      95
Name: Emotion, dtype: int64

In [4]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [5]:
df["Emotion"]=encoder.fit_transform(df['Emotion'])

In [6]:
df.isnull().sum()

Emotion    0
Text       0
dtype: int64

In [7]:
import nltk
import re
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package stopwords to C:\Users\gaurav
[nltk_data]     sahani\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [8]:
corpus = []
lm = WordNetLemmatizer()

In [9]:
df['Text'][5]

'These days he is quite happy travelling by trolley . '

In [10]:
for i in range(0, len(df)):
    
    text = re.sub('[^a-zA-Z]', ' ', df['Text'][i])
    text = text.lower()
    words = text.split()
    words = [word for word in words if word not in set(stopwords.words('english'))]
    words = [lm.lemmatize(word) for word in words]
    text = ' '.join(words)
    corpus.append(text)

In [11]:
corpus[1]

'lennox always truly wanted fight world title happy taking tough route'

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(max_features=1800)
X = tf.fit_transform(corpus).toarray()

In [13]:
X

array([[0.        , 0.        , 0.36074443, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [14]:
y=df[['Emotion']]

In [15]:
y

Emotion
0           3
1           3
2           3
3           3
4           3
...       ...
2409        5
2410        5
2411        5
2412        5
2413        5

[2414 rows x 1 columns]

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=2)

In [47]:
from sklearn.naive_bayes import MultinomialNB
MultiNB= MultinomialNB()
MultiNB.fit(X_train, y_train)

D:\anaconda\envs\Govt\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


MultinomialNB()

In [48]:
y_pred=MultiNB.predict(X_test)
y_pred

array([6, 3, 0, 3, 3, 0, 4, 0, 4, 4, 3, 0, 4, 3, 4, 2, 2, 3, 4, 4, 4, 2,
       0, 4, 4, 0, 3, 3, 3, 4, 2, 0, 0, 2, 0, 3, 4, 6, 4, 0, 3, 3, 0, 3,
       3, 4, 2, 4, 4, 2, 3, 0, 4, 0, 4, 3, 6, 4, 2, 0, 3, 2, 0, 3, 2, 0,
       2, 4, 4, 4, 0, 4, 2, 2, 4, 4, 2, 0, 4, 3, 4, 3, 0, 4, 3, 4, 4, 2,
       0, 4, 2, 3, 0, 4, 0, 0, 0, 4, 4, 0, 0, 3, 3, 2, 2, 2, 4, 3, 3, 2,
       3, 3, 0, 4, 4, 4, 3, 4, 2, 0, 4, 4, 0, 2, 3, 4, 4, 0, 6, 4, 4, 4,
       0, 2, 4, 3, 3, 4, 2, 4, 0, 4, 2, 0, 4, 0, 3, 2, 2, 0, 6, 4, 2, 3,
       0, 0, 4, 4, 0, 4, 2, 3, 3, 4, 2, 4, 0, 4, 0, 4, 4, 4, 4, 3, 3, 0,
       2, 0, 4, 0, 2, 3, 3, 2, 0, 3, 0, 2, 0, 0, 3, 4, 4, 6, 0, 4, 4, 4,
       4, 4, 4, 4, 3, 4, 4, 4, 2, 3, 6, 0, 2, 2, 3, 0, 2, 2, 3, 2, 3, 6,
       2, 3, 4, 3, 4, 4, 3, 3, 3, 2, 0, 4, 2, 2, 4, 0, 0, 4, 4, 4, 0, 2,
       2, 0, 2, 0, 0, 4, 4, 0, 4, 2, 4, 4, 2, 0, 4, 4, 2, 4, 4, 4, 0, 3,
       4, 4, 2, 3, 4, 3, 2, 0, 4, 2, 2, 6, 0, 3, 0, 4, 2, 0, 2, 2, 4, 3,
       4, 0, 3, 3, 4, 2, 4, 2, 3, 0, 0, 3, 2, 2, 2,

In [49]:
from sklearn.metrics import confusion_matrix
confusion_m = confusion_matrix(y_test,y_pred)
confusion_m

array([[ 89,   0,   1,   2,   4,   0,   0],
       [  5,   0,   1,   2,   8,   0,   0],
       [  3,   0,  77,   3,  14,   0,   0],
       [  5,   0,   1,  82,   3,   0,   0],
       [  0,   0,   0,   1, 115,   0,   0],
       [  7,   0,   4,   5,   7,   1,   0],
       [  5,   0,   4,   3,  17,   0,  14]], dtype=int64)

In [50]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.782608695652174

In [53]:
filename = 'govtemotion-model.pkl'
pickle.dump(MultiNB, open(filename, 'wb'))

In [ ]:
def ps(text):
    text = re.sub('[^a-zA-Z]', ' ', df['Text'][i])
    text = text.lower()
    words = text.split()
    words = [word for word in words if word not in set(stopwords.words('english'))]
    words = [lm.lemmatize(word) for word in words]
    text = ' '.join(words)
    text = tf.fit_transform(text).toarray()
    pre = MultiNB.predict(text)
    if pre[0] ='Dipresive':
        return 'Dipresive'
    else:
        return 'Normal'